#!/usr/bin/env bash
# Regenerates k2.sm_80.ptx (PLAN.md, fixture policy). Rerunning on the
# same toolchain is a no-op diff modulo the date line, so a regen diff is
# information: it means the source or the toolchain changed.
set -euo pipefail
cd "$(dirname "$0")"
repo=$(git rev-parse --show-toplevel)
srcdir=$(cd ../src && pwd)
src=$(realpath --relative-to="$repo" "$srcdir/2_coalesced.cuh")
flags="-ptx -lineinfo -frandom-seed=k2 -arch=sm_80"
out=k2.sm_80.ptx
nvcc $flags -I"$srcdir" -o "$out.body" k2.cu
{
    echo "//"
    echo "// Provenance: generated by regen.sh in this directory — do not edit."
    echo "//   source:   $src @ $(git -C "$repo" log -n1 --format=%h -- "$src")"
    echo "//   wrapper:  k2.cu"
    echo "//   compiler: $(nvcc --version | grep release)"
    echo "//   flags:    $flags"
    echo "//   date:     $(date -u +%Y-%m-%d)"
    echo "//"
    cat "$out.body"
} > "$out"
rm "$out.body"
