#!/usr/bin/env bash
# Regenerates the Gluon fixtures (PLAN.md, fixture policy): compile.py runs
# each nanochat entry point once with a fresh Triton cache, and the
# provenance header is prefixed here. Needs torch, triton and a GPU; the
# PTX target is whatever GPU is present, so the file name carries it.
set -euo pipefail
cd "$(dirname "$0")"
repo=$(git rev-parse --show-toplevel)
srcdir=$(cd ../src/gluon && pwd)
tmp=$(mktemp -d)
python3 compile.py "$srcdir" "$tmp" > "$tmp/manifest.tsv"
triton=$(python3 -c 'import triton; print(triton.__version__)')
torch=$(python3 -c 'import torch; print(torch.__version__)')
gpu=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
while IFS=$'\t' read -r name module wrapper; do
    src=$(realpath --relative-to="$repo" "$srcdir/$module")
    arch=$(awk '/^\.target/ { print $2; exit }' "$tmp/$name.ptx")
    {
        echo "//"
        echo "// Provenance: generated by regen.sh in this directory — do not edit."
        echo "//   source:   $src @ $(git -C "$repo" log -n1 --format=%h -- "$src")"
        echo "//   wrapper:  compile.py: $wrapper"
        echo "//   compiler: triton $triton, torch $torch, $gpu"
        echo "//   date:     $(date -u +%Y-%m-%d)"
        echo "//"
        cat "$tmp/$name.ptx"
    } > "$name.$arch.ptx"
done < "$tmp/manifest.tsv"
rm -rf "$tmp"
