#!/usr/bin/env bash
# Regenerates k14.<arch>.ptx (PLAN.md, fixture policy). Rerunning on the
# same toolchain is a no-op diff modulo the date line, so a regen diff is
# information: it means the source or the toolchain changed.
set -euo pipefail
cd "$(dirname "$0")"
repo=$(git rev-parse --show-toplevel)
srcdir=$(cd ../src && pwd)
src=$(realpath --relative-to="$repo" "$srcdir/14_ldmatrix_mma.cuh")
for arch in sm_80; do
    flags="-ptx -lineinfo -frandom-seed=k14 -arch=$arch"
    out=k14.$arch.ptx
    nvcc $flags -I"$srcdir" -o "$out.body" k14.cu
    {
        echo "//"
        echo "// Provenance: generated by regen.sh in this directory — do not edit."
        echo "//   source:   $src @ $(git -C "$repo" log -n1 --format=%h -- "$src")"
        echo "//   wrapper:  k14.cu"
        echo "//   compiler: $(nvcc --version | grep release)"
        echo "//   flags:    $flags"
        echo "//   date:     $(date -u +%Y-%m-%d)"
        echo "//"
        cat "$out.body"
    } > "$out"
    rm "$out.body"
done
