#!/usr/bin/env bash
# Regenerates mma_demo.<arch>.ptx (PLAN.md, fixture policy). Rerunning
# on the same toolchain is a no-op diff modulo the date line, so a regen
# diff is information: it means the source or the toolchain changed.
set -euo pipefail
cd "$(dirname "$0")"
repo=$(git rev-parse --show-toplevel)
src=$(realpath --relative-to="$repo" mma_demo.cu)
for arch in sm_80; do
    flags="-ptx -lineinfo -frandom-seed=mma_demo -arch=$arch"
    out=mma_demo.$arch.ptx
    nvcc $flags -o "$out.body" mma_demo.cu
    {
        echo "//"
        echo "// Provenance: generated by regen.sh in this directory — do not edit."
        echo "//   source:   $src @ $(git -C "$repo" log -n1 --format=%h -- "$src")"
        echo "//   compiler: $(nvcc --version | grep release)"
        echo "//   flags:    $flags"
        echo "//   date:     $(date -u +%Y-%m-%d)"
        echo "//"
        cat "$out.body"
    } > "$out"
    rm "$out.body"
done
